{% set name = "pytest-timeout" %}
{% set version = "2.3.1" %}
{% set hash = "12397729125c6ecbdaca01035b9e5239d4db97352320af155b3f5de1ba5165d9" %}
{% set ext = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ ext }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 1
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - pytest >=7.0.0

test:
  requires:
    - pytest
  imports:
    - pytest_timeout
  commands:
    - py.test --help

about:
  home: https://github.com/pytest-dev/pytest-timeout
  license: MIT
  license_file: LICENSE
  summary: This is a plugin which will terminate tests after a certain timeout.
  description: |
    pytest-timeout is a plugin which will terminate tests after a certain timeout.
    When doing so it will show a stack dump of all threads running at the time.
  dev_url: https://github.com/pytest-dev/pytest-timeout

extra:
  recipe-maintainers:
    - flub
    - nicoddemus
